name: format_bytes
description: Format byte amounts in human readable form.
version: 1.0.0
homepage: https://github.com/Huulivoide/format_bytes
repositiory: https://github.com/Huulivoide/format_bytes
issue_tracker: https://github.com/Huulivoide/format_bytes/issues
author: Jesse Jaara <jesse.jaara@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  intl: ^0.15.7

dev_dependencies:
  test: ^1.0.0
