name: format_bytes
description: Format byte amounts in human readable form. Includes support for localization and custom formatting options.
version: 2.0.0
homepage: https://github.com/Huulivoide/format_bytes
repositiory: https://github.com/Huulivoide/format_bytes
issue_tracker: https://github.com/Huulivoide/format_bytes/issues
author: Jesse Jaara <jesse.jaara@gmail.com>

environment:
  sdk: ">=2.12.0-0 <3.0.0"  

dependencies:
  intl: ^0.17.0

dev_dependencies:
  test: ^1.16.2
