name: format_bytes
description: Format byte amounts in human readable form. Includes support for localization and custom formatting options.
version: 2.1.0
homepage: https://github.com/Huulivoide/format_bytes
repositiory: https://github.com/Huulivoide/format_bytes
issue_tracker: https://github.com/Huulivoide/format_bytes/issues

environment:
  sdk: ">=2.12.0"

dependencies:
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
